name: pylint
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          node-version: '16'
      - name: Test app
        run: |
          pylint --load-plugins=pylint_flask app/

