name: pylint
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pylint
        run: |
          pip install pylint
      - name: Install flask
        run: |
          pip install flask
      - name: Test app
        run: |
          pylint app/app.py

