name: pylint
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install pylint
        run: |
          pip install pylint pylint-flask
      - name: Test app
        run: |
          pylint --load-plugins=pylint_flask app/

